### ISSUE TITLE
Евросеть

### ISSUE THREAD

**Issue by AntonKhorev** [ruosm-presets/literan-moscow#131]
Салоны "Евросеть" ещё остались где-нибудь?

**Comment by literannn** [comment]
Я давно не видел

**Comment by literannn** [comment]
Возможно, стоит удалить Евросеть, группу переименовать в "Электроника" и перенести туда ДНС, Мвидео и Эльдорадо

**Comment by literannn** [comment]
Я все переделал, issue можно закрывать
