### ISSUE TITLE
Протухшая иконка

### ISSUE THREAD

**Issue by deevroman** [ruosm-presets/literan-moscow#147]
https://image.flaticon.com/icons/png/512/47/47421.png

**Comment by literannn** [comment]
Не совсем понимаю. Ссылки на файл с таким именем в заготовках нет...

**Comment by deevroman** [comment]
Вот же https://github.com/ruosm-presets/literan-moscow/blob/c5ade35775527dabeaf7a5d7c36510db85f6e7d6/russian_shops.xml#L3552

**Comment by literannn** [comment]
fixed https://github.com/ruosm-presets/literan-moscow/pull/160
