### ISSUE TITLE
Иконка Почты России использует локальный путь

### ISSUE THREAD

**Issue by deevroman** [ruosm-presets/literan-moscow#148]
В списке заготовок JOSM url заготовки, это ссылка до xml файла, а не до zip архива. Судя по логам,  в таком случае локальный путь не работает:
```
- 00018.546 E: Не удалось найти изображение «pics/icons/Russian_Post.svg»
- 00018.547 W: [NODE, CLOSEDWAY, MULTIPOLYGON] Russian Post: Could not get presets icon pics/icons/Russian_Post.svg
```
Иконка добавлена в https://github.com/ruosm-presets/literan-moscow/commit/58ab901d29d6ce2858ece2ea8ad583d3c439e076

**Comment by literannn** [comment]
что надо сделать, удалить ссылку на иконку?
я эти иконки не проставлял, не в курсе с ними

**Comment by MrYadro** [comment]
Надо RND провести! Мне кажется тогда бы все ссылки не работали

**Comment by MrYadro** [comment]
Фикс сделан
