### ISSUE TITLE
Московские номера (495) поменять на федеральные (800)

### ISSUE THREAD

**Issue by zlant** [ruosm-presets/literan-moscow#20]
Московские номера (495) поменять на федеральные (800) у Спортмастера, Теле2 и других.

**Comment by alexander-ii** [comment]
У спортмастера поменял. У теле2 я не вижу единого федерального номера, там на каждый регион свой местный.
Какие-то еще конкретные или это призыв отсмотреть все (займет какое-то время)? :)

**Comment by zlant** [comment]
Да, это типа призыва заметки, пока только на них наткнулся.

**Comment by alexander-ii** [comment]
Какие нашел - поправил.
