### ISSUE TITLE
combo телефона

### ISSUE THREAD

**Issue by Nemo08** [ruosm-presets/literan-moscow#3]
`<combo key="contact:phone" text="Телефон" default="+7 ххх ххххххх" delete_if_empty="true" />`

Вот эта штука добавляет в объект номер по умолчанию - "+7 ххх ххххххх" - если его не стереть из поля или не вбить нормальный.  Я нигде не нашел шаблоны для ввода, либо подсказки для combo, поэтому предлагаю default="+7 ххх ххххххх" вообще убрать

**Comment by MrYadro** [comment]
combo wombo, надо будет вообще разобраться со всеми тегами. И поменять ссылчку в josm.

**Comment by Zverik** [comment]
Согласен про убрать.
