### ISSUE TITLE
icon not available

### ISSUE THREAD

**Issue by Klumbumbus** [ruosm-presets/literan-moscow#50]
The icon path https://upload.wikimedia.org/wikipedia/ru/b/b5/Logo_stardog%21s.png is not available.

This breaks the JOSM integration test https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/930/jdk=JDK8/testReport/org.openstreetmap.josm.gui.preferences.map/TaggingPresetPreferenceTestIT/testValidityOfAvailablePresets/

Could you please fix this?

**Comment by alexander-ii** [comment]
Sure, thank you for noticing.

**Comment by alexander-ii** [comment]
Done #51.

**Comment by Klumbumbus** [comment]
Thx for the quick fix.
