### ISSUE TITLE
Viktoriya icon not found

### ISSUE THREAD

**Issue by don-vip** [ruosm-presets/literan-moscow#88]
W: [NODE, CLOSEDWAY, MULTIPOLYGON] **Viktoriya**: Could not get presets icon https://upload.wikimedia.org/wikipedia/ru/2/20/Victoria_logo.png

**Comment by don-vip** [comment]
This makes our integration test [fail](https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/2355/jdk=JDK8/testReport/org.openstreetmap.josm.gui.preferences.map/TaggingPresetPreferenceTestIT/testValidityOfAvailablePresets/).

**Comment by don-vip** [comment]
Can you please fix this issue? It's a problem for us having presets failing for a long time. In this case we cannot help because I don't know what "Viktoriya" is, as the icon is no longer available.

**Comment by don-vip** [comment]
Up? It's been more than a week. Without answer we'll disable this presets from our integration tests and stop reporting this kind of issues.

**Comment by Klumbumbus** [comment]
The file was remove from ru wikipedia (non free file) and there seems to be no replacement.
https://ru.wikipedia.org/wiki/%D0%A4%D0%B0%D0%B9%D0%BB:Victoria_logo.png
