### ISSUE TITLE
Replace HTTP by HTTPS

### ISSUE THREAD

**Issue by stoecker** [ruosm-presets/literan-moscow#91]
A lot of the included http links can be replaced by HTTPS.

See https://josm.openstreetmap.de/ticket/16123 of a list - everything where an HTTP error code is listed instead of an SSL error probably supports HTTPS.

**Comment by stoecker** [comment]
Anyone alive?

**Comment by stoecker** [comment]
Ping?

**Comment by MrYadro** [comment]
I'm sorry let me look into that.

**Comment by MrYadro** [comment]
Now it's done, I think

**Comment by alexander-ii** [comment]
Thanks, @MrYadro, and @stoecker 
Is there anything left to fix? May I close this issue?

**Comment by stoecker** [comment]
I checked the mentioned ticket and at least line.me, vkusvill.ru, roskazna.ru, avoska.ru (without www.), dszn.ru (without www.), www.gks.ru, www.rigla.ru, spar.ru (without www.) and www.cofix.ru also support HTTPS and should be changed accordingly.

The Domain x5-express.ru does not work for me in HTTP or HTTPS.

**Comment by alexander-ii** [comment]
@stoecker Thanks again. Will be fixed in the next PR.
