### ISSUE TITLE
Dead/redirect links

### ISSUE THREAD

**Issue by don-vip** [ruosm-presets/literan-moscow#96]
https://github.com/ruosm-presets/literan-moscow/blob/master/russian_shops.xml has dead & redirect links, can you please fix them?

Found HTTP redirection for http://www.mgnl.ru/shops -> 301 -> http://www.mgnl.ru/shops/
Found HTTP redirection for https://www.miuz.ru/stores -> 301 -> https://miuz.ru/stores
Found HTTP redirection for https://www.krasnoeibeloe.ru/address -> 301 -> https://krasnoeibeloe.ru/address
Found HTTP redirection for https://shoko.ru/addresses -> 301 -> http://shoko.ru:443/addresses/
Found HTTP redirection for https://www.aptekamega.ru/pharmacies -> 301 -> http://www.aptekamega.ru:443/pharmacies/
Found HTTP redirection for https://www.dryclean.ru/priemnye_punkty -> 301 -> https://dryclean.ru/priemnye_punkty
Found HTTP redirection for https://victoria-group.ru/company/shops/moskva-i-moskovskaya-oblast -> 302 -> https://victoria-group.ru/company/shops/moskva-i-moskovskaya-oblast/
Found HTTP redirection for https://fix-price.ru/stores -> 301 -> https://fix-price.ru/stores/
Found HTTP redirection for https://www.cafemumu.ru/cafe -> 301 -> https://www.cafemumu.ru/cafe/
Found HTTP redirection for https://www.gemotest.ru/address/moskva -> 301 -> http://www.gemotest.ru:443/address/moskva/
Found HTTP redirection for https://www.adamas.ru/buy -> 301 -> https://www.adamas.ru/buy/
Found HTTP redirection for https://subway.ru/stores -> 301 -> https://subway.ru/stores/
Found HTTP redirection for https://persona.ru/contacts -> 301 -> http://persona.ru/contacts/
Found HTTP redirection for https://megafon.ru/help/offices/#offices -> 302 -> https://moscow.megafon.ru/help/offices/
Found HTTP redirection for https://www.rosbank.ru/ru/offices -> 301 -> https://www.rosbank.ru/ru/offices/
Found HTTP redirection for http://xn--80a4abej.xn--p1ai/karta -> 301 -> /karta/
Found HTTP redirection for https://teremok.ru/places -> 301 -> https://teremok.ru/places/
Found HTTP error for https://mcdonalds.ru/restaurant/map?lat=55.752609&lng=37.61699 -> 404
Found HTTP redirection for https://www.somelie.ru/map -> 301 -> http://www.somelie.ru/map/
Found HTTP redirection for http://litra-beer.ru/magazini -> 301 -> https://litra-beer.ru/magazini
Found HTTP redirection for https://smeshnie-ceny.ru/adresa-magazinov-v-moskve.shtml -> 301 -> https://smeshnie-ceny.ru/adresa-magazinov-v-moskve/
Found HTTP redirection for https://www.dns-shop.ru/shops/moscow -> 301 -> https://www.dns-shop.ru/shops/moscow/
Found HTTP redirection for https://www.detmir.ru/shops -> 301 -> https://www.detmir.ru/shops/
Found HTTP redirection for https://www.invitro.ru/offices/moscow -> 301 -> https://www.invitro.ru/offices/moscow/
Found HTTP redirection for https://moshoztorg.ru/magaziny -> 301 -> http://moshoztorg.ru:443/magaziny/
Found HTTP error for http://kruzhka.ru/addresses/map -> 404
Found HTTP redirection for https://vkusvill.ru/shops -> 301 -> https://vkusvill.ru/shops/
Found HTTP redirection for https://www.podrygka.ru/shoplist -> 301 -> http://www.podrygka.ru/shoplist/
Found HTTP redirection for http://www.kolbasa.ru/where -> 301 -> http://kolbasa.ru/where
Found HTTP redirection for https://www.yakitoriya.ru/restaurants -> 302 -> /ru/restaurants
Found HTTP redirection for https://www.orteka.ru/salon -> 301 -> https://orteka.ru/salon
Found HTTP redirection for https://euroset.ru/shops -> 307 -> https://ohio8.vchecks.me/share/6qPGiIU6q8c1?sid=943&scheme=https&host=euroset.ru&uri=%2fshops%3futm_referrer%3d&t=1570359126901&sad=v%2fX9hI%2bA%3d%3d&uid=oKp7gbe1WPREB8PS&uct=1570359126900&kct=0&m=4&ver=7&flags=642&ua=15453605032911588709&v=lqY46rbxx4hIoQfoeHSlow
Found HTTP redirection for https://amwine.ru/customers/shops -> 301 -> https://amwine.ru/customers/shops/
Found HTTP redirection for https://www.eldorado.ru/info/shops/11324 -> 301 -> https://www.eldorado.ru/info/shops/11324/
Found HTTP redirection for http://ilpatio.ru/restaurants -> 301 -> http://ilpatio.ru/restaurants/
Found HTTP redirection for http://magnit-info.ru/#findShop -> 301 -> https://magnit-info.ru/
Found HTTP redirection for https://www.okmarket.ru/stores -> 301 -> http://www.okmarket.ru/stores/
Found HTTP redirection for https://www.lensmaster.ru/saloni-optiki -> 301 -> https://www.lensmaster.ru/saloni-optiki/
Found HTTP redirection for https://www.raiffeisen.ru/offices -> 301 -> https://www.raiffeisen.ru/offices/
Found HTTP redirection for https://iledebeaute.ru/company/shops -> 301 -> /company/shops/
Found HTTP redirection for https://www.vtb.ru/o-banke/kontakty/otdeleniya -> 301 -> https://www.vtb.ru/o-banke/kontakty/otdeleniya/
Found HTTP redirection for https://avoska.ru/shops -> 301 -> https://avoska.ru/shops/
Found HTTP redirection for https://www.letoile.ru/retail/?city=156&map=yes -> 301 -> https://www.letu.ru/stores?city=156&map=yes
Found HTTP redirection for https://magnitcosmetic.ru/shops -> 302 -> https://magnitcosmetic.ru
Found HTTP redirection for https://topgunbarbershop.ru/barbershop -> 301 -> https://topgunbarbershop.ru/barbershop/
Found HTTP redirection for https://www.cofix.ru/cafe -> 301 -> http://www.cofix.ru/cafe/
Found HTTP redirection for http://glowsubs.ru/restaurants -> 301 -> http://glowsubs.ru/restaurants/
Found HTTP redirection for https://palich.ru/shops -> 301 -> http://palich.ru:443/shops/
Found HTTP redirection for https://moskva.beeline.ru/customers/beeline-map -> 301 -> https://moskva.beeline.ru/customers/beeline-map/
Found HTTP redirection for https://shop.mts.ru/stores -> 301 -> http://shop.mts.ru/stores/
Found HTTP redirection for https://www.gorzdrav.org/apteka/items -> 301 -> https://gorzdrav.org/apteka/items
Found HTTP error for https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dclothes_dryer -> 404
Found HTTP redirection for https://www.myasnov.ru/magaziny_zdorovogo_pitaniya -> 301 -> https://www.myasnov.ru/magaziny_zdorovogo_pitaniya/
Found HTTP redirection for https://www.pizzahut.ru/restaurants -> 301 -> https://pizzahut.ru/restaurants
Found HTTP redirection for https://www.cmd-online.ru/patsientam/gde-sdat-analizy -> 301 -> http://www.cmd-online.ru/patsientam/gde-sdat-analizy/
Found HTTP redirection for https://www.kartoshka.com/map -> 301 -> /map/
Found HTTP redirection for https://pochta.ru/offices -> 301 -> https://www.pochta.ru/offices
Found HTTP redirection for https://apteka366.ru/apteki/map -> 301 -> https://apteka366.ru/apteki/map/
Found HTTP redirection for https://www.sportmaster.ru/stores/moscow -> 301 -> /stores/moscow/
Found HTTP redirection for https://ochkarik.ru/salony-optiki -> 301 -> https://ochkarik.ru/salony-optiki/
Found HTTP redirection for https://sushiwok.ru/msk/addresses -> 301 -> /msk/addresses/
Found HTTP redirection for https://tvoe.ru/shops -> 301 -> https://tvoe.ru/shops/

See https://josm.openstreetmap.de/ticket/17240

**Comment by alexander-ii** [comment]
@don-vip I think all the links except https://euroset.ru/shops were fixed. Every time you open this link it redirects to a different location. See the picture below.

![image](https://user-images.githubusercontent.com/25887642/66539117-b25de900-eb2f-11e9-86db-f9e359a451b1.png)

**Comment by alexander-ii** [comment]
I just have found (https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/3754/testReport/) that https://dryclean.ru/priemnye_punkty/ redirects to itself with 302 code. 

So there are two (the second one — https://euroset.ru/shops) URLs I can do nothing with, except for removing them. What I wouldn't like to do.
